<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260930093000 extends AbstractMigration
{
    public function getDescription(): string { return 'Aligner la génération des identifiants Messenger sur PostgreSQL'; }
    public function up(Schema $schema): void
    {
        if (!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform) { return; }
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('messenger_messages', 'id'), GREATEST(COALESCE(MAX(id), 0), 1), COUNT(*) > 0) FROM messenger_messages");
    }
    public function down(Schema $schema): void
    {
        if (!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform) { return; }
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql("ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval('messenger_messages_id_seq')");
        $this->addSql("SELECT setval('messenger_messages_id_seq', GREATEST(COALESCE(MAX(id), 0), 1), COUNT(*) > 0) FROM messenger_messages");
    }
}
