import fs from 'node:fs';
const ref=name=>({$ref:'#/components/schemas/'+name});const str={type:'string'};const integer={type:'integer'};
const schemas={Error:{type:'object',required:['error'],properties:{error:{type:'object',required:['code','message'],properties:{code:str,message:str}}}},Product:{type:'object',required:['id','name','sku','price','available'],properties:{id:{type:'string',format:'uuid'},productId:{type:'string',format:'uuid'},name:str,slug:str,brand:str,category:str,summary:str,description:str,status:{type:'string',enum:['DRAFT','PUBLISHED','ARCHIVED']},sku:str,price:{type:'integer',minimum:0,description:'Centimes EUR, jamais un flottant',example:32900},currency:{type:'string',enum:['EUR']},available:integer,specs:{type:'object',description:'Champs strictement validés selon la catégorie. Voir /categories.',example:{socket:'NC5',cores:8,frequency:4200,tdp:105,integratedGraphics:true}},images:{type:'array',items:{type:'object',properties:{id:str,url:str,alt:str,primary:{type:'boolean'},position:integer}}}}},Address:{type:'object',required:['name','street','city','postalCode','country'],properties:{name:str,street:str,city:str,postalCode:{type:'string',pattern:'^[0-9]{5}$'},country:{type:'string',enum:['FR']}}},Configuration:{type:'object',required:['components'],properties:{components:{type:'array',maxItems:8,items:{type:'string',format:'uuid'}},budget:{type:'integer',minimum:0,description:'Centimes'},name:str}},Compatibility:{type:'object',properties:{valid:{type:'boolean'},total:integer,items:{type:'array',items:ref('Product')},issues:{type:'array',items:{type:'object',properties:{code:str,severity:{type:'string',enum:['ERROR','WARNING','INFO']},message:str,components:{type:'array',items:str},suggestion:str}}}}},Cart:{type:'object',properties:{items:{type:'array',items:{allOf:[ref('Product'),{type:'object',properties:{quantity:integer,amount:integer,valid:{type:'boolean'}}}]}},subtotal:integer,shipping:integer,total:integer,valid:{type:'boolean'}}},Order:{type:'object',properties:{id:{type:'string',format:'uuid'},number:str,status:{type:'string',enum:['PENDING_PAYMENT','PAID','PREPARING','SHIPPED','DELIVERED','PAYMENT_FAILED','CANCELED','REFUND_PENDING','REFUNDED']},paymentStatus:str,total:integer,shipping:integer,shippingAddress:ref('Address'),delivery:str,tracking:str,lines:{type:'array',items:{type:'object',properties:{name:str,sku:str,unitPrice:integer,quantity:integer,amount:integer}}},history:{type:'array',items:{type:'object',properties:{status:str,actor:str,at:{type:'string',format:'date-time'}}}}}},User:{type:'object',properties:{id:str,email:{type:'string',format:'email'},name:str,roles:{type:'array',items:str},addresses:{type:'array',items:ref('Address')},builds:{type:'array',items:ref('Configuration')}}}};
const paths={};
function add(path,method,summary,response='object',body=null,role='public',description=''){
const params=[...path.matchAll(/\{(\w+)\}/g)].map(m=>({in:'path',name:m[1],required:true,schema:str}));if(!['get','delete'].includes(method)&&!path.endsWith('webhook'))params.push({in:'header',name:'X-CSRF-Token',required:true,schema:str,description:'Obtenu via GET /api/v1/auth/csrf'});
const op={summary,description:(role==='admin'?'ROLE_ADMIN. ':role==='customer'?'Session ROLE_CUSTOMER. ':'Public. ')+description,tags:[path.split('/')[3]||'system'],parameters:params,responses:{'200':{description:'Opération réussie',content:{'application/json':{schema:schemas[response]?ref(response):{type:'object'}}}},'400':{description:'Requête invalide',content:{'application/json':{schema:ref('Error')}}},'401':{description:'Session absente',content:{'application/json':{schema:ref('Error')}}},'403':{description:'CSRF invalide ou permission refusée',content:{'application/json':{schema:ref('Error')}}},'404':{description:'Ressource absente',content:{'application/json':{schema:ref('Error')}}},'409':{description:'Conflit stock, unicité ou transition',content:{'application/json':{schema:ref('Error')}}},'422':{description:'Validation métier',content:{'application/json':{schema:ref('Error')}}},'503':{description:'Service non configuré ou indisponible',content:{'application/json':{schema:ref('Error')}}}}};if(role!=='public')op.security=[{session:[]}];if(body)op.requestBody={required:true,content:{'application/json':{schema:typeof body==='string'?ref(body):body}}};(paths[path]??={})[method]=op;return op;}
const object=properties=>({type:'object',properties});
add('/api/v1/health','get','État du processus API');
const catalog=add('/api/v1/products','get','Rechercher et paginer les variantes publiées');for(const key of ['q','category','brand','sort','stock','min','max','specKey','specValue','page'])catalog.parameters.push({in:'query',name:key,schema:str,description:({sort:'name, price_asc ou price_desc',stock:'true pour limiter au stock disponible',min:'Centimes',max:'Centimes',specKey:'Champ technique autorisé pour la catégorie',specValue:'Valeur exacte',page:'Pagination 12 éléments'}[key]||'Filtre facultatif')});catalog.responses['200'].content['application/json'].schema=object({items:{type:'array',items:ref('Product')},total:integer,page:integer,limit:integer});
add('/api/v1/products/{id}','get','Consulter une variante','Product');add('/api/v1/categories','get','Catégories et schémas des caractéristiques');
add('/api/v1/configurations/check','post','Vérifier une configuration','Compatibility','Configuration');
add('/api/v1/cart','get','Panier et montants recalculés','Cart');add('/api/v1/cart/items/{id}','put','Définir une quantité','Cart',object({quantity:{type:'integer',minimum:0,maximum:10}}));add('/api/v1/cart/items/{id}','delete','Retirer une référence','Cart');add('/api/v1/cart/configuration','post','Valider et ajouter tous les composants atomiquement','Cart','Configuration');
add('/api/v1/auth/csrf','get','Obtenir un jeton CSRF');add('/api/v1/auth/login','post','Connexion par session serveur','object',object({email:str,password:str}));add('/api/v1/auth/register','post','Inscription sans divulgation de compte','object',object({email:{type:'string',format:'email'},name:str,password:{type:'string',minLength:12,maxLength:128}})).responses['202']={description:'Demande traitée sans révéler l’existence du compte'};add('/api/v1/auth/logout','post','Déconnexion et invalidation de session');
add('/api/v1/me','get','Profil privé','User',null,'customer');add('/api/v1/me/profile','patch','Modifier son nom','User',object({name:str}),'customer');add('/api/v1/me/password','post','Changer son mot de passe','object',object({currentPassword:str,password:{type:'string',minLength:12}}),'customer');add('/api/v1/me/addresses','post','Ajouter une adresse','User','Address','customer');add('/api/v1/me/addresses/{id}','delete','Supprimer une adresse','User',null,'customer');add('/api/v1/me/configurations','post','Enregistrer une configuration valide','User','Configuration','customer');
const checkout=add('/api/v1/checkout','post','Réserver le stock et créer Stripe Checkout','object',object({address:ref('Address'),delivery:{type:'string',enum:['standard','express']}}),'customer','Aucun prix ni total du client n’est accepté. Réutiliser la même clé après une erreur réseau.');checkout.parameters.push({in:'header',name:'Idempotency-Key',required:true,schema:{type:'string',minLength:16,maxLength:80}});checkout.responses['201']={description:'Session Stripe test créée',content:{'application/json':{schema:object({order:str,url:{type:'string',format:'uri'}})}}};
add('/api/v1/orders','get','Commandes du client','object',null,'customer');add('/api/v1/orders/{id}','get','Snapshot et suivi de commande','Order',null,'customer','Propriétaire ou administrateur exclusivement (Voter).');add('/api/v1/orders/{id}/subscription','post','Autoriser un topic Mercure privé','object',null,'customer');
const webhook=add('/api/v1/payments/webhook','post','Recevoir un événement Stripe signé','object',object({id:str,type:str,livemode:{type:'boolean',enum:[false]},data:{type:'object'}}),'public','Exemption CSRF ; signature obligatoire sur le corps brut, horodatage vérifié.');webhook.parameters.push({in:'header',name:'Stripe-Signature',required:true,schema:str});
for(const [path,summary]of [['dashboard','Indicateurs calculés sur les commandes'],['products','Catalogue incluant brouillons et archives'],['orders','Commandes administratives'],['stock/{id}/history','Historique des ajustements']])add('/api/v1/admin/'+path,'get',summary,'object',null,'admin');
add('/api/v1/admin/products','post','Créer un produit et sa variante','Product','Product','admin');add('/api/v1/admin/products/{id}','put','Modifier ou archiver un produit','Product','Product','admin');add('/api/v1/admin/stock/{id}','post','Ajuster le stock physique','object',object({quantity:{type:'integer',minimum:0},reason:{type:'string',minLength:3}}),'admin');add('/api/v1/admin/orders/{id}/transition','post','Faire progresser la préparation','Order',object({transition:{type:'string',enum:['prepare','ship','deliver']},tracking:str}),'admin');add('/api/v1/admin/orders/{id}/refund','post','Demander un remboursement intégral test','Order',null,'admin','Montant intégral serveur, clé Stripe stable, confirmation par webhook. Pas de remise en stock automatique.');
add('/api/v1/media/{name}','get','Lire une image validée');const upload=add('/api/v1/admin/products/{id}/images','post','Importer une image raster','Product',null,'admin');upload.requestBody={required:true,content:{'multipart/form-data':{schema:object({image:{type:'string',format:'binary'},alt:str})}}};add('/api/v1/admin/products/{id}/images/{name}','patch','Ordonner et décrire une image','Product',object({alt:str,position:integer}),'admin');add('/api/v1/admin/products/{id}/images/{name}','delete','Retirer une image du produit','Product',null,'admin');
add('/api/v1/configurations/options','post','Options compatibles avec la sélection','object','Configuration');
add('/api/v1/admin/products/{id}/variants','post','Créer une variante commerciale','Product',object({name:str,sku:str,price:integer}),'admin');
add('/api/v1/me/addresses/{id}','patch','Modifier une adresse privée','User','Address','customer');
add('/api/v1/me/configurations/{id}','delete','Supprimer une configuration sauvegardée','User',null,'customer');
add('/api/v1/cart/configurations/{id}','put','Remplacer une configuration du panier atomiquement','Cart','Configuration');
add('/api/v1/cart/configurations/{id}','delete','Retirer une configuration en conservant les unités séparées','Cart');
schemas.Cart.properties.groups={type:'array',items:object({id:str,name:str,components:{type:'array',items:str}})};
checkout.requestBody.content['application/json'].schema.properties.expectedLines={type:'array',minItems:1,maxItems:50,items:{type:'object',required:['id','price','quantity'],properties:{id:str,price:integer,quantity:integer}}};
checkout.requestBody.content['application/json'].schema.required=['address','delivery','expectedLines'];
checkout.description='Session ROLE_CUSTOMER. Les lignes attendues servent uniquement à détecter un changement : les prix facturés viennent du serveur. Un conflit QUOTE_CHANGED exige relecture et nouvelle confirmation. Réutiliser la même clé après une erreur réseau.';
for(const key of ['q','status','from','to','page'])paths['/api/v1/admin/orders'].get.parameters.push({in:'query',name:key,schema:str,description:({q:'Numéro, email ou suivi',from:'Date incluse AAAA-MM-JJ',to:'Date incluse AAAA-MM-JJ',page:'20 commandes par page'}[key]||'État de commande')});
for(const path of Object.values(paths))for(const [method,operation]of Object.entries(path)){if(method==='delete')operation.parameters.push({in:'header',name:'X-CSRF-Token',required:true,schema:str});}
fs.writeFileSync('docs/openapi.json',JSON.stringify({openapi:'3.0.3',info:{title:'BuildCore API',version:'1.0.0',description:'Démonstration e-commerce, produits fictifs et Stripe test uniquement.'},servers:[{url:'http://localhost:8000',description:'API locale'}],paths,components:{securitySchemes:{session:{type:'apiKey',in:'cookie',name:'BUILDCORE_SESSION'}},schemas}},null,2));
